repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # flake8 is mainly used to check some static error
  - repo: local
    hooks:
      - id: flake8
        name: Run flake8
        entry: flake8
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: black
        name: Run black
        entry: black
        language: system
        types: [python]
